[package]
name = "whiteboard"
version = "2.0.0"
edition = "2024"

description = "A simple GTK4 whiteboard app made with Rust"
repository = "https://github.com/StellarSt0rm/whiteboard"
license = "MIT"

[dependencies]
gtk4 = "0.9.6"
libadwaita = "0.7.2"
