[package]
name = "whiteboard"
version = "2.0.0"
edition = "2024"

description = "A simple GTK4 whiteboard app made with Rust"
repository = "https://github.com/StellarSt0rm/whiteboard"
license = "AGPL-3.0-only"

[dependencies]
gtk4 = "0.9.6"
libadwaita = "0.7.2"
