name: Build and Release

on: [workflow_dispatch]

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Nix
        uses: cachix/install-nix-action@v18

      - name: Setup Nix Shell
        uses: rrbutani/use-nix-shell-action@v1
        with:
          devShell: .

      - name: Build with Cargo
        run: cargo build --release

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "$tag" \
              "./target/release/whiteboard#whiteboard-linux" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${tag#v}" \
              --draft
