name: Build and Release

on:
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Nix
      uses: cachix/install-nix-action@v14

    - name: Install dependencies and build with Nix
      run: |
        nix-channel --add https://nixos.org/channels/nixpkgs-unstable nixpkgs  # Add the channel explicitly
        nix-channel --update
        nix-shell --pure --run "cargo build --release"

    - name: Create GitHub Release
      id: create_release
      run: |
        gh release create "" "./target/release/whiteboard#whiteboard-linux" --draft
